### ISSUE TITLE
After copying polyfillet.lua ipe.exe does not start

### ISSUE THREAD

**Issue by vargabalint92** [AndrewMartchenko/my-ipelets#1]
Hi everybody,

i just wondering why ipe.exe does not want to start:
I downloaded and copied the polyfillet.lua file in the iplets folder after that i could not start the ipe.exe. I am on windows 10 and ipe version is 7.2.7.

Could somebody help me?

Thanks a lot,
Balint

**Comment by AndrewMartchenko** [comment]
Hi,
I cannot reproduce this issue. I also have windows 10 and ipe version 7.2.7.
Does ipe load if you remove the polyfillet.lua file?
Regards,

Andrew M.

**Comment by vargabalint92** [comment]
Hi,

it works. My browser must have not correctly downloaded the polyfillet.lua.... it was strange.
It works like a charm! 
Thank you!
Balint
